# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 18:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0003_auto_20200108_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='colors',
            field=models.CharField(default=b'#FFF', max_length=6, validators=[django.core.validators.RegexValidator(b'^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', b'Give the hexidecimal value of this color')]),
        ),
    ]
