# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0004_auto_20200108_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(default=b'SOME-PATTERN', max_length=15, unique=True),
        ),
    ]
