# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 18:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0005_auto_20200108_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='speed_var',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
